AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Egress Inspection using AWS Cloud WAN and AWS Network Firewall. Templates creates 
  AWS Cloud WAN global and core Network with core network base policy.

Resources:
  GlobalNetwork:
    Type: AWS::NetworkManager::GlobalNetwork
    Properties:
      Description: Global Network - Inspection Scenarios
      Tags: 
        - Key: Name
          Value: cwan-inspection-global-network
  
  CoreNetwork:
    Type: AWS::NetworkManager::CoreNetwork
    Properties:
      Description: Core Network - Inspection Scenarios
      GlobalNetworkId: !Ref GlobalNetwork
      Tags: 
        - Key: Name
          Value: cwan-inspection-global-network
      PolicyDocument: 
        version: "2021.12"
        core-network-configuration:
          vpn-ecmp-support: true
          asn-ranges:
            - 64520-64525
          edge-locations:
            - location: us-east-2
            - location: eu-central-1
        segments:
          - name: Production
            require-attachment-acceptance: false
          - name: Development
            require-attachment-acceptance: false
        network-function-groups:
          - name: InspectionNFG
            require-attachment-acceptance: false
        segment-actions:
          - action: share
            mode: attachment-route
            segment: Development
            share-with:
              - Production
          - action: send-to
            segment: Production
            via:
              network-function-groups:
                - InspectionNFG
        attachment-policies:
          - rule-number: 100
            condition-logic: or
            conditions:
              - type: tag-exists
                key: domain
            action:
              association-method: tag
              tag-value-of-key: domain

Outputs:
  CoreNetworkId:
    Description: Core Network ID.
    Value: !GetAtt CoreNetwork.CoreNetworkId
  CoreNetworkArn:
    Description: Core Network ARN.
    Value: !GetAtt CoreNetwork.CoreNetworkArn